### PR TITLE
resolves #37 limits the script to only accessing the current document

### LINKED ISSUE #37: limit permissions
Can you add this to the top of addon.gs so that you only need permission to access the current document?

```
/**
 * @OnlyCurrentDoc  Limits the script to only accessing the current document.
 */
```

### PR DESCRIPTION
**Pull request by ggrossetie**
resolves #37

### CODE REVIEW

**Comment by Mogztter** [comment]
@evbacher  Could you please confirm that this is correct?

**Review by evbacher — COMMENTED** [review]
Yes, this should do it. Once you make this change to the addon, let me know and I can try installing it and verify for sure.

**Comment by Mogztter** [comment]
Ok thanks I will try to publish the addon later tonight (UTC +2)

**Comment by Mogztter** [comment]
@evbacher It should be OK. For the record, the publishing process is *very* confusing and not straightforward at all!
Could you please confirm that the new version is published? It should be version 15.
Thanks.

**Comment by evbacher** [comment]
I installed your addon and the new permission is in effect. Thanks!

I agree -- the new publishing process took me a while to figure out too. Once you get the URL to the G Suite Marketplace (https://console.cloud.google.com/apis/api/appsmarket-component.googleapis.com/overview) then add your project ID, you can update the description with the Publish item, and the version with the Configuration item.

**Comment by Mogztter** [comment]
Excellent news!
Indeed, once you get that URL it's OK 👍

**Pull request merged**
