### PR TITLE
Add hyperlink formatting

### PR DESCRIPTION
**Pull request by briandominick**
All elements tested with getLinkUrl(), non nulls get formatted

### CODE REVIEW

**Comment by Mogztter** [comment]
Thanks again!
I will test this new feature locally then merge if everything is working.

**Comment by Mogztter** [comment]
This is working great, thanks :+1:

**Comment by Mogztter** [comment]
@briandominick Version 13 is available, let me know if this is working.

**Comment by briandominick** [comment]
Yup! Awesome!

**Pull request merged**
